export const letters = ["Q", "W", "E", "A", "S", "D", " Z", "X", "C"];

const files = [
  "../../sounds/bass/7rystan-trap_bass_01.wav",
  "../../sounds/bass/7rystan-trap_bass_02.wav",
  "../../sounds/bass/7rystan-trap_bass_03.wav",
  "../../sounds/bass/7rystan-trap_bass_04.wav",
  "../../sounds/bass/7rystan-trap_bass_05.wav",
  "../../sounds/bass/7rystan-trap_bass_06.wav",
  "../../sounds/bass/7rystan-trap_bass_07.wav",
  "../../sounds/bass/7rystan-trap_bass_08.wav",
  "../../sounds/bass/7rystan-trap_bass_09.wav",
  "../../sounds/bass/7rystan-trap_bass_10.wav",
  "../../sounds/bass/7rystan-trap_bass_11.wav",
  "../../sounds/bass/18/7rystan-trap_bass_12.wav",
  "../../sounds/bass/7rystan-trap_bass_13.wav",
  "../../sounds/bass/18/7rystan-trap_bass_14.wav",
  "../../sounds/bass/7rystan-trap_bass_15.wav",
  "../../sounds/bass/18/7rystan-trap_bass_16.wav",
  "../../sounds/bass/18/7rystan-trap_bass_17.wav",
  "../../sounds/bass/7rystan-trap_bass_18.wav",
  "../../sounds/bass/18/7rystan-trap_bass_19.wav",
  "../../sounds/bass/7rystan-trap_bass_20.wav",
  "../../sounds/bass/18/7rystan-trap_bass_21.wav",
  "../../sounds/bass/slap-E1.wav",
  "../../sounds/bass/slap-E2.wav",
  "../../sounds/bass/slap-E3.wav",
  "../../sounds/bass/synrez-A-C1.wav",
  "../../sounds/bass/synrez-A-C2.wav",
  "../../sounds/bass/synrez-A-E1.wav",
  "../../sounds/bass/synrez-A-E2.wav",
  "../../sounds/bass/synrez-A-Gsharp1.wav",
  "../../sounds/bass/synrez-A-Gsharp2.wav",
  "../../sounds/bass/tight-square-A2.wav",
  "../../sounds/bass/tight-square-B4.wav",
  "../../sounds/bass/tight-square-C2.wav",
  "../../sounds/bass/tight-square-C3.wav",
  "../../sounds/bass/tight-square-Csharp4.wav",
  "../../sounds/bass/tight-square-Fsharp4.wav",
  "../../sounds/bass/tight-square-G1.wav",
  "../../sounds/bass/tight-square-Gsharp1.wav",
];

export const audioLocationForLetters = {
  Q: files[0],
  W: files[1],
  E: files[2],
  A: files[3],
  S: files[4],
  D: files[5],
  Z: files[6],
  X: files[7],
  C: files[8],
};
